// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: proto/analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextAnalysisService_AnalyzeText_FullMethodName = "/TextAnalysisService/AnalyzeText"
)

// TextAnalysisServiceClient is the client API for TextAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Performs batch sentiment analysis.
type TextAnalysisServiceClient interface {
	// Returns one result per input text, preserving request order.
	AnalyzeText(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type textAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextAnalysisServiceClient(cc grpc.ClientConnInterface) TextAnalysisServiceClient {
	return &textAnalysisServiceClient{cc}
}

func (c *textAnalysisServiceClient) AnalyzeText(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, TextAnalysisService_AnalyzeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextAnalysisServiceServer is the server API for TextAnalysisService service.
// All implementations must embed UnimplementedTextAnalysisServiceServer
// for forward compatibility.
//
// Performs batch sentiment analysis.
type TextAnalysisServiceServer interface {
	// Returns one result per input text, preserving request order.
	AnalyzeText(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedTextAnalysisServiceServer()
}

// UnimplementedTextAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextAnalysisServiceServer struct{}

func (UnimplementedTextAnalysisServiceServer) AnalyzeText(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeText not implemented")
}
func (UnimplementedTextAnalysisServiceServer) mustEmbedUnimplementedTextAnalysisServiceServer() {}
func (UnimplementedTextAnalysisServiceServer) testEmbeddedByValue()                             {}

// UnsafeTextAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextAnalysisServiceServer will
// result in compilation errors.
type UnsafeTextAnalysisServiceServer interface {
	mustEmbedUnimplementedTextAnalysisServiceServer()
}

func RegisterTextAnalysisServiceServer(s grpc.ServiceRegistrar, srv TextAnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedTextAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextAnalysisService_ServiceDesc, srv)
}

func _TextAnalysisService_AnalyzeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextAnalysisServiceServer).AnalyzeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextAnalysisService_AnalyzeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextAnalysisServiceServer).AnalyzeText(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextAnalysisService_ServiceDesc is the grpc.ServiceDesc for TextAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TextAnalysisService",
	HandlerType: (*TextAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeText",
			Handler:    _TextAnalysisService_AnalyzeText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analysis.proto",
}
