# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\"\x1f\n\x0e\x41nalyzeRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"=\n\x0e\x41nalysisResult\x12\x11\n\tsentiment\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\"O\n\x0f\x41nalyzeResponse\x12 \n\x07results\x18\x01 \x03(\x0b\x32\x0f.AnalysisResult\x12\x1a\n\x12processing_time_ms\x18\x02 \x01(\x05\x32G\n\x13TextAnalysisService\x12\x30\n\x0b\x41nalyzeText\x12\x0f.AnalyzeRequest\x1a\x10.AnalyzeResponseB\x0fZ\rgateway/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rgateway/proto'
  _globals['_ANALYZEREQUEST']._serialized_start=18
  _globals['_ANALYZEREQUEST']._serialized_end=49
  _globals['_ANALYSISRESULT']._serialized_start=51
  _globals['_ANALYSISRESULT']._serialized_end=112
  _globals['_ANALYZERESPONSE']._serialized_start=114
  _globals['_ANALYZERESPONSE']._serialized_end=193
  _globals['_TEXTANALYSISSERVICE']._serialized_start=195
  _globals['_TEXTANALYSISSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
